import React from 'react';

const ArticlePhoto = ({ photo }) => {
  return (
    <figure>
      <img className="main-article-image" src={photo.imageUrl} alt={photo.altText} />
      <figcaption>
        Generated by&nbsp;
        <a href="https://en.wikipedia.org/wiki/DALL-E" target='_blank'>Dall-E 2</a>
      </figcaption >
    </figure>
  );
};

export default ArticlePhoto;
