article:
  attributes:
    - active
    - section
    - featured
    - highlighted
  associations:
    - author
    - photo
author:
  attributes:
    - name
  associations:
    - article
comment:
  attributes:
  associations:
    - user
    - article

