require "rails_helper"

RSpec.describe OpenAi::Gateway do
  describe "::generate_image" do
    let(:prompt) { Faker::Lorem.sentence }
    let(:image_url) { Faker::Internet.url }
    let(:image_string) { Faker::Alphanumeric.alpha }

    before do
      allow(OpenAi::Model::Dalle).to receive(:generate_image_url).
        with(prompt).and_return(image_url)
      allow(OpenAi::ImageFetcher).to receive(:get).
        with(image_url).and_return(image_string)
    end

    it "returns the image generated by the specified model" do
      expect(described_class.generate_image(prompt: prompt)).
        to eq(image_string)
    end
  end
end
